name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Runs all steps on the VM
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'pnpm'

      - run: pnpm i --frozen-lockfile
      - run: pnpm test
